server:
  port: 8080

spring:
  application:
    name: umbrella_db
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/umbrella_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: never

# Porta removida - configurada no início do arquivo

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework: INFO
# Configuração do Google
google:
  api:
    key: ${GOOGLE_API_KEY:AIzaSyAWOO-efpqfd9rfJ_7z1vsFbtzvtiR4D2E}

# Configuração PayPal (corrigida para usar kebab-case)
paypal:
  mode: live
  client-id: AbWHZSjRti6nJOR1llh1bJjDj2GUklE1xT3BeYq4JRlwTKQYz9Ohf8fVUrTe2SwRW0NatLaFxJl1_wV4
  client-secret: EM1HqI8zcLE-sTUn3xvrZXs4TMN1AYsH55YNQLeYYUCEQD_9-N_QrvbnjXH_6RAK5fushzfHTzJ3tyYc


# OpenWeather configuration
openweather:
  api:
    key: ${OPENWEATHER_API_KEY:7d7353b5a696a31078211f46891b389e}
    units: metric
    lang: pt


